[project]
name = "poetry-lambda-plugin"
version = "2.1.2"
description = "The plugin for poetry that enables you to build zip packages suitable for serverless deployment on platforms like AWS Lambda, Google App Engine, Azure App Service, and more..."
authors = [
    {name = "Michał Murawski",email = "mmurawski777@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9,<4.0"
dependencies = [
    "docker (>=7.1.0,<8.0.0)"
]

[tool.poetry]
packages = [{include = "poetry_plugin_lambda_build"}]

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.6"
pytest = "^8.0.1"
poetry = "^2.0.0"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
