---
name: Set up Poetry
description: Sets up Poetry for a given version of Python and install project dependencies
inputs:
  python-version:
    description: The version of Python to use
    required: true
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: poetry.lock
    - name: Install Poetry and project dependencies
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 - --version 1.8.3
        poetry config virtualenvs.create false
        poetry install
      shell: sh
