name: Run Tests
on:
  workflow_call:
    inputs:
      python-version:
        type: string
      runs-on:
        type: string
        default: "ubuntu-latest"


jobs:
  tests:
    name: Run Tests for python${{ inputs.python-version }} on ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry==2.1.1
          poetry config virtualenvs.create false
          poetry install
      - name: Install
        run: poetry install --with dev
      - name: Run Lint and Format
        run: |
          poetry run ruff check
      - name: Run Pytest
        run: poetry run pytest