name: Run Tests

on: [pull_request, workflow_dispatch]

jobs:
  test_python310:
    secrets: inherit
    uses: ./.github/workflows/run_tests_linux.yml
    with:
      python-version: "3.10"
  test_python313:
    secrets: inherit
    uses: ./.github/workflows/run_tests_linux.yml
    with:
      python-version: "3.13"